apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "capt.fullname" . }}-controller-manager
  labels:
    cluster.x-k8s.io/provider: infrastructure-tinkerbell
    control-plane: controller-manager
  {{- include "capt.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "capt.fullname" . }}-controller-manager
  labels:
    cluster.x-k8s.io/provider: infrastructure-tinkerbell
    control-plane: controller-manager
  {{- include "capt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-tinkerbell
      control-plane: controller-manager
    {{- include "capt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: infrastructure-tinkerbell
        control-plane: controller-manager
      {{- include "capt.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        env:
        - name: TINKERBELL_IP
          value: {{ .Values.controllerManager.manager.tinkerbellIp }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: {{ include "capt.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: capt-webhook-service-cert