apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "capt.fullname" . }}-manager-role
  labels:
    cluster.x-k8s.io/provider: infrastructure-tinkerbell
  {{- include "capt.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  - machines/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - tinkerbellclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - tinkerbellclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - tinkerbellmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - tinkerbellmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tinkerbell.org
  resources:
  - hardware
  - hardware/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tinkerbell.org
  resources:
  - templates
  - templates/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tinkerbell.org
  resources:
  - workflows
  - workflows/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "capt.fullname" . }}-manager-rolebinding
  labels:
    cluster.x-k8s.io/provider: infrastructure-tinkerbell
  {{- include "capt.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "capt.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "capt.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'